from app.model.user import User
from app.model.patient import Patient
from app.model.inhospital import InHospital
from app.model.department import Department
from app.model.medicine import Medicine
from app.model.vaccine import Vaccine
from app.model.assay import Assay
from app.model.case import Case
from app.model.role import Role
from app.model.case_type import CaseType
from app.model.choice import Choice
from app.model.testpaper import TestPaper
from app.model.exam import Exam
