sudo: enabled
language: python
python:
- 3.6
cache: pip
notifications:
  email:
    recipients: 
  on_success: never
  on_failure: always
install:
- pip install pipenv
- pipenv install --dev
script:
- export APP_SETTINGS=app.config.TestingConfig
- pipenv run nosetests -w tests --with-coverage --cover-package=app
after_success:
- coveralls
deploy:
  provider: heroku
  app: frozen-retreat-73403
  api_key:
    secure: nlW1EMjBtnNIlidxuGg62mm7nTaO0Osq3eojwFJp0hz3/LcVxgDhhALxAE+8+7lDaQ240DLFM/ranrmntzF8GtVSHu7717axO5iGqBKToVrtNeeVEkNxkuv21HfneVNT7UIsy6HGoarH2uEpzT9pxEXVSS4rfnUM+UEuQGQPzaf8HLTnIfVdB1HB/YO/6cN/pgBID/59P3hhQdrj6YmPND2IkYMEUCR5cdNSPC779JbgiTx/zcUIUuWrsZ/aDEmXvtjgrMnDORM8gsjwLQFfrs1uC/pCTD+P6rjQ4FUlzSkRHi43KSg0kbBlJzf+s+OQ5SK7jrSxTg4rLFQkq9kyIaW8cQXS39sAuaIYij3B6W3WyGsuHNKbEwWsaRiysLDbhZO7OWZ+w1l+B+YUtA47O/RvqCHesBrqhWZIdnPv5z2KVoLGQWZSd47Uu8FonRHsrjMpQGAJNjM6o9lYgg9Ti6AJ0tBTeVNqkiRDWfI83/7E7nLwJ5XqqcmCwb2y1O9qa3WoSNMSOoKwRNALFyncUQnf2j3NsXCUVd7NbH9FCcz6OpkXsvLbiOJ2aRKZnXw36TrHKUaNi1bYV+NINzfbZUfW1mCc/7H2q+kyF5lxMm5dPBm0M9Wfaq8Ni9jIVecwULNli39sf2310RwjQ9WnUu7yp7D+08+ypyAJi5ul2NQ=
  run:
  - pipenv run python manage.py init_db
