sudo: enabled

language: python

python:
  - 3.6

notifications:
  email:
    recipients:
      
  on_success: never
  on_failure: always

install:
  - pip install -r requirements.txt
before_install: 

script:
  - python -W ignore::DeprecationWarning -m unittest -v api_test/login_api_test.py
  - python -W ignore::DeprecationWarning -m unittest -v api_test/user_api_test.py

before_deploy: 

deploy:
