sudo: enabled

language: python

python:
  - 3.6
  - master

notifications:
  email:
    recipients:
      
  on_success: never
  on_failure: always

install:
  - pip install -r requirements.txt
before_install: 

script:
  - python Test.py

before_deploy: 

deploy:
