sudo: enabled

language: python

python:
  - 3.6.x
  - master

notifications:
  email:
    recipients:
      
  on_success: never
  on_failure: always

install:
  - pip install requirements.txt
before_install: 

script:
  - python test.py

before_deploy: 

deploy: