version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: >
     bash -c "python manage.py init_db &&
              gunicorn app:app -w4 -b0.0.0.0:8000 --access-logfile -"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db